import jsPDF from 'jspdf';
import type { Job } from '@/types/job';
import { format } from 'date-fns';

export function generateJobPdf(job: Job, companyName: string) {
  const doc = new jsPDF();
  const margin = 14;
  let y = 20;

  doc.setFontSize(18);
  doc.setTextColor(79, 110, 247);
  doc.text('BookaWaka', margin, y);
  y += 8;
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(companyName, margin, y);
  y += 12;

  doc.setFontSize(14);
  doc.setTextColor(0);
  doc.text(`Trip Receipt #${job.id}`, margin, y);
  y += 10;

  doc.setFontSize(10);
  const lines = [
    `Status: ${job.status}`,
    `Source: ${job.source}`,
    `Passenger: ${job.passengerName}`,
    `Phone: ${job.passengerPhone}`,
    `Pickup: ${job.pickAddress}`,
    `Dropoff: ${job.dropAddress}`,
    `Driver: ${job.driverName || job.driverId || '—'}`,
    `Vehicle: ${job.vehicleNo || job.vehicleId || '—'}`,
    `Payment: ${job.paymentType}`,
    `Fare: $${job.totalFare || job.estimatedFare || '0.00'}`,
    `Booked: ${job.bookingDateTime}`,
    job.completedAt ? `Completed: ${format(new Date(job.completedAt), 'PPpp')}` : '',
  ].filter(Boolean);

  for (const line of lines) {
    doc.text(line, margin, y);
    y += 6;
    if (y > 270) {
      doc.addPage();
      y = 20;
    }
  }

  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text('Generated by BookaWaka Dispatch', margin, 285);
  doc.save(`bookawaka-trip-${job.id}.pdf`);
}
